steps:
  # Build the image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'PYTHON_VERSION=3.10.11',
        '-t',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/singa-backend/singa-predict-api:latest',
        '.',
      ]
    env:
      - DOCKER_BUILDKIT=1

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/singa-backend/singa-predict-api:latest',
      ]

  # Deploy the new image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
        'run',
        'deploy',
        'singa-predict-api',
        '--image',
        'asia-southeast2-docker.pkg.dev/$PROJECT_ID/singa-backend/singa-predict-api:latest',
        '--region',
        'asia-southeast2',
        '--min-instances',
        $_MIN_INSTANCES,
        '--memory',
        $_MEMORY,
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--port',
        $_CUSTOM_PORT,
        '--service-account',
        $SERVICE_ACCOUNT_EMAIL,
        # Set required env
        '--set-env-vars',
        'HOST=${_HOST}',
        '--set-env-vars',
        'MODEL_PATH=models/${_MODEL_NAME}',
        # Set the env secrets
        '--set-secrets',
        'GCLOUD_STORAGE_BUCKET=bucket-name:latest',
      ]

# Configure build log
logsBucket: gs://$_LOGBUCKET_NAME
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/$_SERVICE_ACCOUNT'

# Substitution Value
substitutions:
  _HOST: '0.0.0.0'
  _CUSTOM_PORT: '4000'
  _MIN_INSTANCES: '1'
  _MEMORY: 4Gi
  _MODEL_NAME: your-model-name
  _SERVICE_ACCOUNT: your-sa-for-build
  _LOGBUCKET_NAME: your-log-bucket-name
options:
  logging: GCS_ONLY
  dynamicSubstitutions: true

images:
  - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/singa-backend/singa-predict-api:latest'
